name: mentor_me
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0+1

  enum_to_string: ^2.0.1
  meta: ^1.7.0

  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  firebase_analytics: ^10.0.7
  firebase_storage: ^11.0.8

  flutter_bloc: ^7.0.0
  equatable: ^2.0.3

  image_cropper: ^3.0.1
  image_picker: ^0.8.4+4

  intl: ^0.17.0
  timeago: ^3.1.0
  uuid: ^3.0.5
  flutter_countdown_timer: ^4.1.0
  sms_autofill: ^2.2.0
  google_sign_in: ^5.2.4
  intl_phone_field: ^3.1.0
  flutter_facebook_auth: ^5.0.6
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  timer_button: ^2.0.0
  animations: ^2.0.2
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  connectivity: ^3.0.6
  stream_chat_flutter: ^4.6.0
  dart_jsonwebtoken: ^2.4.1
  percent_indicator: ^4.2.2
  flutter_timer_countdown: ^1.0.3
  animated_text_kit: ^4.2.2
  page_transition: ^2.0.5
  otp_text_field: ^1.1.3
  flutter_neumorphic: ^3.2.0
  google_nav_bar: ^5.0.6
  fluttericon: ^2.0.0
  share_plus: ^4.0.10
  rolling_switch: ^0.0.2
  url_launcher: ^6.1.5
  showcaseview: ^2.0.0+1
  shared_preferences: ^2.0.15
  lottie: ^1.4.0
  image_stack: ^2.1.1
  flutter_speed_dial: ^6.0.0
  timelines: ^0.1.0
  provider: ^6.0.3
  connectivity_plus: ^2.3.6+1
  http: ^0.13.5
  flutter_stripe: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
